version: '3'
services:
  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_cron_db
      POSTGRES_PASSWORD: postgres_pass
